<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CustomEntity\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Duzhi.Common" Version="3.2.3.2" />
  </ItemGroup>

</Project>
